### ISSUE TITLE
Portal Sys Reqs page isn't translated in Polski

### ISSUE THREAD

**Issue by wowallace** [jen-jackson/l10n-arcmap-certification#12]
* Language: Polski, Nederlands
* URL: http://serverstg.arcgis.com/pl/portal/latest/install/linux/portal-for-arcgis-system-requirements.htm,
http://serverstg.arcgis.com/nl/portal/latest/install/linux/portal-for-arcgis-system-requirements.htm

* Topic title (EN): Portal for ArcGIS 10.5 system requirements
* Topic GUID: [TopicGUID](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=TopicGUID)
* Publication GUID:
* Screenshot:
![image](https://cloud.githubusercontent.com/assets/6921233/23238227/da268e38-f915-11e6-8fc9-025cc3c7a771.png)
Issue description:
Pages/URL's above appear in English, whereas the topic below in the TOC is translated?

### High priority
- [ ] Versioning switcher functions
    - [ ] Content remains in same language as origin
    - [ ] "Other versions" text is translated
- [ ] TOC appears and functions as expected for each publication
- [ ] Content appears for each topic 
    - [ ] Product names are generally not translated
- [ ] Structure looks correct
- [ ] Banner says "ArcMap"
- [ ] Steps appear as expected, with numbers
- [ ] Notes and tips appear correctly
- [ ] Spot check links in topics
	
### Extra
- [ ] Table layouts are correct (if applicable)
- [ ] Alt text appears when the mouse cursor hovers over an image
    Russian and Chinese all
- [ ] Check for broken image references 
- [ ] Screenshots localized in RU, ZH-CN, JA; English for other languages
- [ ] Breadcrumb is translated
- [ ] "Back to top" is translated
- [ ] Search text is translated
- [ ] Feedback link is translated
    - [ ] Takes user to translated Feedback page 
- [ ] All elements in footer are translated except those circled below in yellow:
![Footer](https://cloud.githubusercontent.com/assets/5480934/23227402/ab5b9c56-f8ed-11e6-9a09-68f73fcd9600.png)

**Comment by michi6571** [comment]
@wowallace Thank you for the report. 
This is expected since the Portal Install Guide is out of scope for Polish.  
I will close the issue.
