### ISSUE TITLE
Spanish home tab - Links pointing to English Pro site

### ISSUE THREAD

**Issue by jen-jackson** [jen-jackson/l10n-arcmap-certification#17]
* Language: Spanish
* URL: http://desktopstg.arcgis.com/es/arcmap/
* Topic title (EN): Home tab
* Topic GUID: N/A
* Publication GUID: N/A
* Screenshot:
![image](https://cloud.githubusercontent.com/assets/5480934/23273914/b08f9fba-f9b5-11e6-9c0b-c81121b8412a.png)

Issue description:
The links in the paragraph point to the English site for Pro instead of Spanish.

\cc: @michi6571

**Comment by michi6571** [comment]
@timjormo Thank you for the report.  We will fix it at 10.5.1.

**Comment by michi6571** [comment]
I will close the issue.
