### ISSUE TITLE
Workflow Manager shows English for some languages

### ISSUE THREAD

**Issue by rgarrity** [jen-jackson/l10n-arcmap-certification#2]
* Language: ja, fr, de
* URL: http://desktopstg.arcgis.com/ja/arcmap/latest/extensions/workflow-manager/a-quick-tour-of-workflow-manager.htm 
* Topic title (EN): A quick tour of ArcGIS Workflow Manager, and other topics.
* Topic GUID: [GUID-82354BE6-0154-4DA2-8B7E-17C9E83A2D4A](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=GUID-82354BE6-0154-4DA2-8B7E-17C9E83A2D4A)
* Publication GUID: GUID-B865C65C-C2A8-485E-8F86-7EE97F8AB758
* Screenshot: 
![image](https://cloud.githubusercontent.com/assets/7049342/23226759/a4adcf34-f8eb-11e6-83a7-115d3683e8e4.png)

Issue description:
English appears on pages that should display in Japanese, German, and French. Maybe Workflow Manager isn't supposed to be translated into those languages?

**Comment by michi6571** [comment]
@rgarrity Thank you for the report.   This text in the versioning switcher does not come from CMS file.  We can't manage the translation per publication level whether should be translated or not.  I will close the issue as known limitation.
