### ISSUE TITLE
Nearly all database connection topics in Spanish include "ArcGIS for Server" instead of "ArcGIS Server"

### ISSUE THREAD

**Issue by kimberly-peter** [jen-jackson/l10n-arcmap-certification#25]
* Language: Spanish
* URL: http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-altibase.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-dameng.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-db2.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-informix.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-sqlserver.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-netezza.htm,
 http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-oracle.htm,  http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-postgresql.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-saphana.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/databases/connect-teradata.htm
* Topic title (EN): Connect to ALTIBASE from ArcGIS, Connect to Dameng from ArcGIS, Connect to DB2 from ArcGIS, Connect to Informix from ArcGIS, Connect to Microsoft SQL Server from ArcGIS, Connect to Netezza from ArcGIS, Connect to Oracle from ArcGIS, Connect to PostgreSQL from ArcGIS, Connect to SAP HANA from ArcGIS, Connect to Teradata from ArcGIS
* Topic GUID: [TopicGUID](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=TopicGUID)
GUID-6B64534B-A0C2-440A-BDD3-F1A75FBD1CE4, GUID-9CA03717-A9BE-44BA-8012-1E32A0E014C4, GUID-8A5D8E40-9BBE-4776-9F44-6F23587ECE56, GUID-BCCF1E43-F53F-4A1E-95D3-7000BCC3E654, GUID-A3E493AB-CB09-4C87-B04F-67036E98EB98, GUID-9ADF4678-49B7-454E-9719-FBEB652587F1, GUID-ED618EFE-2A76-476C-B614-D9BA50A834E7, GUID-98E60091-7399-4A17-AE78-34BAE06CE95B, GUID-39F83CC7-650A-452E-92B9-F8ED891BF2B1, GUID-51D1EB6B-E1A0-4CCB-9A46-C16FDDCFFD6F
* Publication GUID: GUID-A95C1131-525D-4014-8448-E181F06C6217
* Screenshot:
![image](https://cloud.githubusercontent.com/assets/8865041/23284924/e4db96d4-f9e2-11e6-81f6-5586f193ea27.png)
![image](https://cloud.githubusercontent.com/assets/8865041/23284948/092e1156-f9e3-11e6-8f34-0c91419da7eb.png)

Issue description: Most of the database connection topics in the Spanish version of database topics have the wrong product name for ArcGIS Server.

\cc: @michi6571

**Comment by michi6571** [comment]
@kimberly-peter Thank you for the report.  We will fix the product names as soon as possible.

**Comment by michi6571** [comment]
Fixed on STG. I will closed the issue.
