### ISSUE TITLE
General comment: French translating "Server" portion of ArcGIS Server at 10.5 in some places

### ISSUE THREAD

**Issue by kimberly-peter** [jen-jackson/l10n-arcmap-certification#39]
* Language: French
* URL: Example URLs:
http://desktopstg.arcgis.com/fr/arcmap/latest/manage-data/gdbs-in-oracle/connect-oracle.htm
http://desktopstg.arcgis.com/fr/arcmap/latest/manage-data/databases/connect-sqlserver.htm#ESRI_SECTION1_34B6DCC7273741CDAA403DA01EF83742
http://serverstg.arcgis.com/fr/portal/latest/administer/windows/about-using-your-server-with-portal-for-arcgis.htm
In this one, it shows up 3 different ways: http://serverstg.arcgis.com/fr/server/latest/administer/windows/the-arcgis-server-account.htm
* Topic title (EN): 
* Topic GUID: [TopicGUID](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=TopicGUID)
* Publication GUID: 
* Screenshot:
Issue description: ArcGIS Server is the product name.  When the product name was ArcGIS for Server, they did not translate "Server".  It doesn't seem like the Server portion of ArcGIS Server should be translated either since it's the name of the product.  They're not translating it in all places, but some.  For example, not translated here (scroll to bottom): http://desktopstg.arcgis.com/fr/arcmap/latest/manage-data/gdbs-in-oracle/connect-oracle-read-only.htm or here: http://serverstg.arcgis.com/fr/server/latest/administer/windows/securing-your-arcgis-server-site.htm

\cc: @michi6571

**Comment by michi6571** [comment]
@kimberly-peter Thank you for the report.  We will fix it as soon as possible.

**Comment by michi6571** [comment]
Fixed on STG.  I will close the issue.
