### ISSUE TITLE
Topic not translated

### ISSUE THREAD

**Issue by kimberly-peter** [jen-jackson/l10n-arcmap-certification#42]
* Language: German, Spanish, French, Japanese, Russian, Chinese
* URL: http://desktopstg.arcgis.com/de/arcmap/latest/manage-data/metadata/illustrated-guide-to-complete-fgdc-metadata.htm, http://desktopstg.arcgis.com/es/arcmap/latest/manage-data/metadata/illustrated-guide-to-complete-fgdc-metadata.htm, http://desktopstg.arcgis.com/ja/arcmap/latest/manage-data/metadata/illustrated-guide-to-complete-fgdc-metadata.htm, http://desktopstg.arcgis.com/fr/arcmap/latest/manage-data/metadata/illustrated-guide-to-complete-fgdc-metadata.htm, http://desktopstg.arcgis.com/ru/arcmap/latest/manage-data/metadata/illustrated-guide-to-complete-fgdc-metadata.htm, http://desktopstg.arcgis.com/zh-cn/arcmap/latest/manage-data/metadata/illustrated-guide-to-complete-fgdc-metadata.htm
* Topic title (EN): Illustrated guide to complete FGDC metadata
* Topic GUID: [TopicGUID](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=TopicGUID)
GUID-F85ABF30-2016-4873-BC18-4E64FE0B11D5
* Publication GUID: GUID-4303441C-1344-4435-96FA-06DD8D13C3D6
* Screenshot:

Issue description:
Topic in English in all publications.

\cc: @michi6571

**Comment by michi6571** [comment]
@kimberly-peter Thank you for the report.  This is known issue; the topic has been set to "no" for the translation management by the author.  It should stay in English .
