### ISSUE TITLE
Portal for ArcGIS publication only partially translated for Nederlands.

### ISSUE THREAD

**Issue by sarasanchez** [jen-jackson/l10n-arcmap-certification#43]
* Language: Nederlands
* URL: http://serverstg.arcgis.com/nl/portal/latest/administer/windows/choosing-between-an-arcgis-online-subscription-and-portal-for-arcgis.htm
* Topic title (EN): Not a single title but several topics in this publication
* Topic GUID: [TopicGUID](GUID-43C59EAA-621E-4E6A-A6C3-CF021169FDBF)
* Publication GUID: GUID-86E3206A-3CAD-43C1-9F16-FFB7CA3AEC71
* Screenshot:

![image](https://cloud.githubusercontent.com/assets/6364255/23372389/4e8d0424-fcd0-11e6-9d15-153a9ae7d71f.png)

Issue description:
Many topics are translated here but many are not.

### High priority
- [ ] Versioning switcher functions
    - [ ] Content remains in same language as origin
    - [ ] "Other versions" text is translated
- [ ] TOC appears and functions as expected for each publication
- [ ] Content appears for each topic 
    - [ ] Product names are generally not translated
- [ ] Structure looks correct
- [ ] Banner says "ArcMap"
- [ ] Steps appear as expected, with numbers
- [ ] Notes and tips appear correctly
- [ ] Spot check links in topics
	
### Extra
- [ ] Table layouts are correct (if applicable)
- [ ] Alt text appears when the mouse cursor hovers over an image
    Russian and Chinese all
- [ ] Check for broken image references 
- [ ] Screenshots localized in RU, ZH-CN, JA; English for other languages
- [ ] Breadcrumb is translated
- [ ] "Back to top" is translated
- [ ] Search text is translated
- [ ] Feedback link is translated
    - [ ] Takes user to translated Feedback page 
- [ ] All elements in footer are translated except those circled below in yellow:
![Footer](https://cloud.githubusercontent.com/assets/5480934/23227402/ab5b9c56-f8ed-11e6-9a09-68f73fcd9600.png)

\cc: @michi6571

**Comment by michi6571** [comment]
@sarasanchez Thank you for the report.  Sorry, the pub list under wiki doesn't contain full-set of language of the Portal publications.  But, this is expected for NL and PL.  Both admin guide for Windows & Linux are out of scope for the translation.  The sections should stay in English (except for shared topics/paragraphs from the other supported pubs).

**Comment by michi6571** [comment]
I will close the issue.
