### ISSUE TITLE
ArcGIS Data Store installation guide topic and map not translated

### ISSUE THREAD

**Issue by kimberly-peter** [jen-jackson/l10n-arcmap-certification#44]
* Language: Spanish, French, Russian, and Chinese
* URL: http://serverstg.arcgis.com/es/data-store/latest/install/windows/welcome-to-arcgis-data-store-installation-guide.htm
http://serverstg.arcgis.com/fr/data-store/latest/install/windows/welcome-to-arcgis-data-store-installation-guide.htm
http://serverstg.arcgis.com/es/data-store/latest/install/linux/welcome-to-arcgis-data-store-installation-guide.htm
http://serverstg.arcgis.com/fr/data-store/latest/install/linux/welcome-to-arcgis-data-store-installation-guide.htm
http://serverstg.arcgis.com/ru/data-store/latest/install/windows/welcome-to-arcgis-data-store-installation-guide.htm
http://serverstg.arcgis.com/ru/data-store/latest/install/linux/welcome-to-arcgis-data-store-installation-guide.htm
http://serverstg.arcgis.com/zh-cn/data-store/latest/install/windows/welcome-to-arcgis-data-store-installation-guide.htm
http://serverstg.arcgis.com/zh-cn/data-store/latest/install/linux/welcome-to-arcgis-data-store-installation-guide.htm
Topic title (EN): Welcome to the ArcGIS Data Store (Windows) installation guide and Welcome to the ArcGIS Data Store (Linux) installation guide
Topic GUID: GUID-DA2AD3B3-5B58-4033-A70E-C03E9C7688B9
Map GUID: GUID-CD2703FC-CFE2-4C70-9746-24588AA888B4
Publications:  GUID-840AE9C4-8E5B-436A-BC77-26F8AA8DDE96 (Linux) GUID-63BE2DC8-C71A-4F52-9BB9-0EA576AF0ED0 (Windows)
Screenshot: Topic title in map not translated:
![image](https://cloud.githubusercontent.com/assets/8865041/23376374/afbb5646-fce0-11e6-9276-c92519f6f639.png)
Issue description:  One topic and the Windows version of the map not translated.

\cc: @michi6571

**Comment by michi6571** [comment]
@kimberly-peter Thank you for the report.  This is expected.  The publications should not be translated to ES, FR, RU, and zh-CN even though there are some translated topics/paragraphs which are shared with other supported publications.  I will closed the issue.
