### ISSUE TITLE
Portions of Upgrade ArcGIS Data Store not translated for several languages

### ISSUE THREAD

**Issue by kimberly-peter** [jen-jackson/l10n-arcmap-certification#45]
* Language: Spanish, French, Russian, Chinese
* URL: http://serverstg.arcgis.com/es/data-store/latest/install/windows/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F, http://serverstg.arcgis.com/es/data-store/latest/install/linux/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F, http://serverstg.arcgis.com/fr/data-store/latest/install/windows/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F, http://serverstg.arcgis.com/fr/data-store/latest/install/linux/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F, http://serverstg.arcgis.com/ru/data-store/latest/install/windows/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F, http://serverstg.arcgis.com/ru/data-store/latest/install/linux/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F, http://serverstg.arcgis.com/zh-cn/data-store/latest/install/windows/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F, http://serverstg.arcgis.com/zh-cn/data-store/latest/install/linux/upgrading-an-earlier-version-of-arcgis-data-store.htm#GUID-E4EF13D0-3DBC-42F7-B86F-C5BF88C2BF0F
* Topic title (EN): Upgrade ArcGIS Data Store
* Topic GUID: [TopicGUID](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=TopicGUID)
GUID-8323F649-7871-44EC-87EA-8E4D624710C0
* Publication GUID: GUID-63BE2DC8-C71A-4F52-9BB9-0EA576AF0ED0 (Windows) GUID-840AE9C4-8E5B-436A-BC77-26F8AA8DDE96 (Linux)
* Screenshot:
Issue description: Contents in two subsections--Upgrade using an interactive wizard-driven experience and Silently upgrade using commands--not translated.

\cc: @michi6571

**Comment by michi6571** [comment]
@kimberly-peter Thank you for the report.  This is expected.  The publications are not supported for es, fr, ru, and zh-CN.  There are some translated contents/paragraphs in the sections due to shared topics/paragraphs with other supported publications.

**Comment by michi6571** [comment]
I will close the issue.
