### ISSUE TITLE
ArcGIS for Desktop appears on ArcMap Sys Req's map and topic, French only

### ISSUE THREAD

**Issue by wowallace** [jen-jackson/l10n-arcmap-certification#6]
* Language: French
* URL: http://desktopstg.arcgis.com/fr/system-requirements/latest/arcgis-desktop-system-requirements.htm
* Topic title (EN): Configuration système requise de ArcGIS for Desktop 10.5
* Topic GUID: [TopicGUID](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=TopicGUID)
* Publication GUID:
* Screenshot:
![image](https://cloud.githubusercontent.com/assets/6921233/23228731/7b213c12-f8f2-11e6-83fe-90549e1dec43.png)

Issue description:
Map (TOC) and Title should be ArcGIS Dektop, not ArcGIS for Desktop

### High priority
- [ ] Versioning switcher functions
    - [ ] Content remains in same language as origin
    - [ ] "Other versions" text is translated
- [ ] TOC appears and functions as expected for each publication
- [ ] Content appears for each topic 
    - [ ] Product names are generally not translated
- [ ] Structure looks correct
- [ ] Banner says "ArcMap"
- [ ] Steps appear as expected, with numbers
- [ ] Notes and tips appear correctly
- [ ] Spot check links in topics
	
### Extra
- [ ] Table layouts are correct (if applicable)
- [ ] Alt text appears when the mouse cursor hovers over an image
    Russian and Chinese all
- [ ] Check for broken image references 
- [ ] Screenshots localized in RU, ZH-CN, JA; English for other languages
- [ ] Breadcrumb is translated
- [ ] "Back to top" is translated
- [ ] Search text is translated
- [ ] Feedback link is translated
    - [ ] Takes user to translated Feedback page 
- [ ] All elements in footer are translated except those circled below in yellow:
![Footer](https://cloud.githubusercontent.com/assets/5480934/23227402/ab5b9c56-f8ed-11e6-9a09-68f73fcd9600.png)

**Comment by michi6571** [comment]
@wowallace Thank you for the report.  The issue has been fixed on STG.

**Comment by michi6571** [comment]
Closed
