### ISSUE TITLE
ArcGIS for Inspire 10.5 Sys Req's not translated, but was at 10.4

### ISSUE THREAD

**Issue by wowallace** [jen-jackson/l10n-arcmap-certification#8]
* Language: Ru, Jp, Ch
* URL: http://desktopstg.arcgis.com/ru/system-requirements/latest/arcgis-for-inspire-system-requirements.htm

* Topic title (EN): ArcGIS for INSPIRE system requirements
* Topic GUID: [TopicGUID](https://devtopia.esri.com/ArcGISPro/help-feedback/search?type=Issues&utf8=✓&q=TopicGUID)
* Publication GUID:
* Screenshot: 
10.5: 
![image](https://cloud.githubusercontent.com/assets/6921233/23229288/9e56bc3c-f8f4-11e6-9672-61791ab7dc54.png)
10.4: 
![image](https://cloud.githubusercontent.com/assets/6921233/23229311/b2696544-f8f4-11e6-9642-5c7fdff1f075.png)

Issue description: Ru, Jp, and Ch shows up in English at 10.5, but was translated at 10.4?

### High priority
- [ ] Versioning switcher functions
    - [ ] Content remains in same language as origin
    - [ ] "Other versions" text is translated
- [ ] TOC appears and functions as expected for each publication
- [ ] Content appears for each topic 
    - [ ] Product names are generally not translated
- [ ] Structure looks correct
- [ ] Banner says "ArcMap"
- [ ] Steps appear as expected, with numbers
- [ ] Notes and tips appear correctly
- [ ] Spot check links in topics
	
### Extra
- [ ] Table layouts are correct (if applicable)
- [ ] Alt text appears when the mouse cursor hovers over an image
    Russian and Chinese all
- [ ] Check for broken image references 
- [ ] Screenshots localized in RU, ZH-CN, JA; English for other languages
- [ ] Breadcrumb is translated
- [ ] "Back to top" is translated
- [ ] Search text is translated
- [ ] Feedback link is translated
    - [ ] Takes user to translated Feedback page 
- [ ] All elements in footer are translated except those circled below in yellow:
![Footer](https://cloud.githubusercontent.com/assets/5480934/23227402/ab5b9c56-f8ed-11e6-9a09-68f73fcd9600.png)

**Comment by michi6571** [comment]
@wowallace Thank you for the report.  Since RU, JA, zh-CN should not be translated for INSPIRE help, the translated 10.4 topic has been reverted back to English on STG which match with 10.5.

**Comment by michi6571** [comment]
I will close the issue.
